# Generated by Django 6.0.6 on 2026-07-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AfricaCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capital', models.CharField(max_length=100)),
                ('population', models.PositiveIntegerField()),
                ('area', models.FloatField(help_text='Area in square kilometers')),
                ('official_language', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(choices=[('NORTH', 'Northern Africa'), ('WEST', 'Western Africa'), ('CENT', 'Central Africa'), ('EAST', 'Eastern Africa'), ('SOUTH', 'Southern Africa')], max_length=100)),
            ],
            options={
                'verbose_name': 'African Country',
                'verbose_name_plural': 'African Countries',
                'ordering': ['name'],
            },
        ),
    ]
